name: CI (Client + Server)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  client:
    name: Build & Test Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Build frontend
        working-directory: client
        run: npm run build

      

  server:
    name: Build & Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker for Testcontainers
        run: |
          sudo systemctl start docker || true
          docker ps

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'  
      - name: Restore backend dependencies
        working-directory: .
        run: dotnet restore

      - name: Build backend
        working-directory: .
        run: dotnet build DeadPigeon.sln --configuration Release --no-restore

      - name: Test backend
        working-directory: .
        env:
          DOTNET_NOLOGO: true
        run: dotnet test DeadPigeon.sln --configuration Release --no-build --verbosity normal
